# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - iearn-finance/yearn-vaults@0.3.2

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    remappings:
      - "@yearnvaults=iearn-finance/yearn-vaults@0.3.2"
      - "@openzeppelin=deps/@openzeppelin"

reports:
  exclude_contracts:
    - SafeMath
    - SafeMathUpgradeable
    - AccessControlUpgradeable
    - EnumerableSetUpgradeable
    - SafeERC20Upgradeable
    - ERC20Upgradeable
